### ISSUE TITLE
[BUG] SSL connection problem with Cient Certificates Auth

### ISSUE THREAD

**Issue by EdEngineering** [opensearch-project/opensearch-py#484]
### What is the bug?
When trying to connect to OpenSearch Instace with client certificate and key i get this error:

```
opensearchpy.exceptions.SSLError: ConnectionError([SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:2635)) caused by: SSLError([SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:2635))
```

OpenSearch logs shows this, i believe to be relevant
```
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Empty client certificate chain
```

### How can one reproduce the bug?
- Configure a docker compose file to create a Opensearch instance with basic auth and client certificate auth enabled. With the next configuration files.
- and then i've run the securityadmin.sh bash

opensearch.yml
```
cluster.name: os-cluster
network.host: 0.0.0.0

bootstrap.memory_lock: "true" # along with the memlock settings below, disables swapping

plugins.security.allow_unsafe_democertificates: true
plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.pemtrustedcas_filepath: certificates/ca/ca.pem
plugins.security.ssl.http.clientauth_mode: REQUIRE
plugins.security.ssl.transport.enabled: true
plugins.security.ssl.transport.pemtrustedcas_filepath: certificates/ca/ca.pem
plugins.security.ssl.transport.enforce_hostname_verification: false


plugins.security.authcz.admin_dn:
  - CN=ADMIN,O=ORG,L=XXXXXXXXX,ST=XXXXXXXXX,C=XX
plugins.security.nodes_dn:
  - CN=node1,O=ORG,L=XXXXXXXXX,ST=XXXXXXXXX,C=XX

plugins.security.audit.type: internal_opensearch
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
cluster.routing.allocation.disk.threshold_enabled: false

```

config.yml
```
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
    authc:
      internal_auth:
        order: 0
        description: "HTTP basic authentication using the internal user database"
        http_enabled: true
        transport_enabled: true
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: internal
      clientcert_auth_domain:
        description: "Authenticate via SSL client certificates"
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: clientcert
          config:
            username_attribute: cn #optional, if omitted DN becomes username
          challenge: false
        authentication_backend:
          type: noop

```

### What is the expected behavior?
It's expected to authenticate correctly with opensearch and make the connection.

### What is your host/environment?
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"

### Do you have any additional context?
I've try connecting just with curl client, and javascript client and it works fine, so its not related to the certificates.
